name: SJeonP
title: SJeonP's GitBlog
description: SJeonP's GitBlog
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: sj.park@ivpl.sookmyung.ac.kr
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
